### ISSUE TITLE
extension: sidebar issues on certain sites (e.g. truncation/scrolling/etc)

### ISSUE THREAD

**Issue by karlicoss** [karlicoss/promnesia#102]
Feel free to comment here if you find more such examples

- [ ] https://arthurperret.fr/2020/05/22/ecrire-et-editer/ (@bepolymathe)
      same for Hypothesis, so potentially site markup is somehow unusual
- [ ] https://www.quaternum.net (@bepolymathe)
      possibly something to do with Jekyll?
- [ ] https://psychonautwiki.org/wiki/Cannabidiol (sidebar detaches when scrolled)
- [ ] https://www.bloomberg.com/europe (might be behind popups) https://github.com/karlicoss/promnesia/issues/146#issue-727850381

**Comment by bepolymathe** [comment]
Hi @karlicoss, 
Just another site with same issue for me 
[https://www.quaternum.net](https://www.quaternum.net)
I notice that these two sites are static blogs generated by [Jekyll](https://jekyllrb.com) :thinking:

**Comment by karlicoss** [comment]
Another one, sidebar detaches when scrolled https://psychonautwiki.org/wiki/Cannabidiol

**Comment by yoyurec** [comment]
> https://www.arthurperret.fr/blog/2022-04-11-pourquoi-tenir-un-blog-scientifique.html (@bepolymathe)
> same for Hypothesis, so potentially site markup is somehow unusual

they have own styles for `IFRAME` - margin, max-height, etc...
as devs we can reset it in `extension\src\sidebar-outer.css`, as users in options page css:
```
.promnesia-sidebar-active #promnesia-frame {
    margin: 0;
    padding: 0;
    max-width: none;
    max-height: none;
}
```

---

> https://www.quaternum.net/ (@bepolymathe)

will be fixed with https://github.com/karlicoss/promnesia/pull/308

---

> https://www.bloomberg.com/europe (might be behind popups)

will be fixed with https://github.com/karlicoss/promnesia/pull/308

---

> https://psychonautwiki.org/wiki/Cannabidiol (sidebar detaches when scrolled)

their `BODY` has `transform: translateZ(0);` which un-fix sidebar ((
https://stackoverflow.com/questions/15194313/transform3d-not-working-with-position-fixed-children

as devs we can reset it in `extension\src\sidebar-outer.css`, as users in options page css:
```
body.promnesia-sidebar-active {
    transform: none;
}
```
...but will it safe for other sites? IMHO yes - only crazy sites will use transform on body )) 
and extension will apply styles only when sidebar opened!
