### ISSUE TITLE
cbuijs/shallalist is no longer available, failing browser extension.

### ISSUE THREAD

**Issue by hytor-yang** [karlicoss/promnesia#325]
Environment: macOS Chrome 101.0.4951.64.

Thanks a lot for the great tool. I did not realize how helpful it is in my daily work until it stopped working (*☻-☻*)

Per some basic debug, failing in fetching [cbuijs/shallalist banking domains](https://raw.githubusercontent.com/cbuijs/shallalist/master/finance/banking/domains) threw uncaught exception ([filterlist.js#L81](https://github.com/karlicoss/promnesia/blob/3a1ce4c3d7d50adf8d9fe4499336845a676fc22b/extension/src/filterlist.js#L81)). And it is confirmed the service provider announced DISCONTINUED.

We may need an alternative list for #2, or temporarily live without the security guard?

**Comment by karlicoss** [comment]
Oh wow thanks for letting me know! :) 

Obviously a problem in the extension that it's failing in such way, I'll think how to fix that properly. 

The real cause seems to be that they renamed `master` branch to `main`, and somehow some (but not all) of the filter files are missing from older `master` branch for now. Putting something like this in your settings should fix it for you for now.

```
[
  ["Webmail",
   "https://raw.githubusercontent.com/cbuijs/shallalist/main/webmail/domains"        ],
  ["Banking",
   "https://raw.githubusercontent.com/cbuijs/shallalist/main/finance/banking/domains"]
]
```

I'll work on the patch in the meantime and will push it asap.

**Comment by karlicoss** [comment]
Ok, Firefox fix already released! 
Chrome version will probably take longer to get approved unfortunately :(

**Comment by karlicoss** [comment]
ah also looks like the breaking change was reversed and `main` branch deleted, so hopefully everything will just work now no matter the version :sweat_smile:

**Comment by hytor-yang** [comment]
Glad to see it back. Thanks for the quick fix.
